### ISSUE TITLE
Your repo doesn't contain the Eclipse Project 

### ISSUE THREAD

**Issue by shamoon1997** [Daoud-Hussain/University-Management-System#3]
When we clone the project. We are not able to run this project. Can you upload the Project correctly with proper project structure.

**Comment by thatdevopsengineer** [comment]
Apologies for the issue but I've cloned and run the project again and it is
working perfectly. We have a "Main.java" file that we have to run for the
execution of the project. Compile and run "Main.java" and Project will work
perfectly.
I've added the Compilation and Running method in the README as well for
convenience. Thanks!

**Comment by shamoon1997** [comment]
@Daoud-Hussain Thank you man. I was trying to run it through Intellija Ide. So, now running it through command line it is working. Thanks man appreciated.
